---
- name: This is to remove users.  BE CAREFUL
  hosts: all
  gather_facts: no
  ignore_unreachable: true
  vars:
    users:
      - younassed
  tasks:
    - name: Remove all listed users
      user:
        name: "{{ item }}"
        state: absent
      with_items:  "{{ users }}"
      become: true
