---
- name: User administration
  hosts: all
  vars:
    users: "{{ lookup('pipe', 'ls -1 keys/') }}"
  tasks:
      
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      become: true

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true
      
    - name: Add the user with a primary group of 'sudo'
      user:
        name: "{{ item }}"
        groups: sudo, wheel
        shell: /bin/bash
        createhome: yes
        append: yes
      with_items:  "{{ users }}"
      become: true
    
    - name: Deploy SSH Key
      authorized_key: 
        user: "{{ item }}"
        key: "{{ lookup('file', './keys/{{ item }}') }}"
        state: present
      with_items:  "{{ users }}"
      become: true
    
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      become: true
