---
- name: User administration
  hosts: all
  vars:
    directory: ./keys/
  tasks:
    - command: "ls {{directory}}"
      register: dir_out
      
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      become: true

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true
      
    - name: Add the user 'lakotam' with a primary group of 'sudo'
      user:
        name: "{{ item }}"
        groups: sudo, wheel
        shell: /bin/bash
        createhome: yes
        append: yes
      with_items:  dir_out.stdout_lines
      become: true
    
    - name: Deploy SSH Key
      authorized_key: 
        user: "{{ item }}"
        key: "{{ lookup('file', './keys/{{ item }}') }}"
        state: present
      with_items:  dir_out.stdout_lines
      become: true
    
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      become: true
