---
name: 'AWX'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  AddUsers:
    runs-on: ubuntu-latest
    steps:
      - name: AWX
        uses: fitbeard/action-trigger-awx@v23.3.0
        with:
          tower_url: awx.atgfw.com
          tower_token: ${{ secrets.AWX_TOKEN }}
          resource_type: job_template
          resource_name: Add Users
          job_type: run
    
    
    
